// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlE8IOAzejP5eK_frm1b74T9cPS9SfETY',
    appId: '1:21491853608:web:a00c523e5f36f938bf481d',
    messagingSenderId: '21491853608',
    projectId: 'fooddeliver1',
    authDomain: 'fooddeliver1.firebaseapp.com',
    storageBucket: 'fooddeliver1.firebasestorage.app',
    measurementId: 'G-739YTLM9RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKYRoQGOWazBTcMW7KMho_a_h9A0-HpPc',
    appId: '1:21491853608:android:65100c04cb5148acbf481d',
    messagingSenderId: '21491853608',
    projectId: 'fooddeliver1',
    storageBucket: 'fooddeliver1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHinC9I0cXarpDQWab9auBAvIDxVglSMc',
    appId: '1:21491853608:ios:f8477bf28a70e4c3bf481d',
    messagingSenderId: '21491853608',
    projectId: 'fooddeliver1',
    storageBucket: 'fooddeliver1.firebasestorage.app',
    iosBundleId: 'com.example.flutterRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHinC9I0cXarpDQWab9auBAvIDxVglSMc',
    appId: '1:21491853608:ios:f8477bf28a70e4c3bf481d',
    messagingSenderId: '21491853608',
    projectId: 'fooddeliver1',
    storageBucket: 'fooddeliver1.firebasestorage.app',
    iosBundleId: 'com.example.flutterRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlE8IOAzejP5eK_frm1b74T9cPS9SfETY',
    appId: '1:21491853608:web:9e6de4835793e6a2bf481d',
    messagingSenderId: '21491853608',
    projectId: 'fooddeliver1',
    authDomain: 'fooddeliver1.firebaseapp.com',
    storageBucket: 'fooddeliver1.firebasestorage.app',
    measurementId: 'G-3M9Z98WH2H',
  );
}
